# src/models/health_models.py

from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class MotivationRequest(BaseModel):
    # Optional user identifier (used in tests/fixtures)
    user_id: Optional[str] = None

    # Core fields used by build_prompt and the agent
    previous_data: str
    current_data: str
    action_taken: str
    next_action: str
    goal: str
    progress: str

    # Free-form user preferences/instructions
    custom_instruction: str = ""


class MotivationResponse(BaseModel):
    # Main motivational message generated by the agent
    prompt: str

    # Keep as list[dict] to match existing usage in tests (r['title'], r['url'])
    web_results: List[Dict[str, str]] = Field(default_factory=list)
    youtube_videos: List[Dict[str, str]] = Field(default_factory=list)


# Optional: keep a simple health metrics model for future use/extension
class HealthMetrics(BaseModel):
    weight: Optional[float] = None          # in kg or lbs (caller decides)
    steps: Optional[int] = None
    calories_burned: Optional[int] = None
    workouts_completed: Optional[int] = None
    date: Optional[str] = None               # ISO date string
